import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
import https from 'node:https';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {cfg,login,request} from './live-client.mjs';
import {chromium} from '/home/vmware/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const run=promisify(execFile),cookie=await login();const result={status:'IN_PROGRESS',checks:[]};const pass=n=>{result.checks.push(n);console.log('PASS',n);};
const envfile='runtime/admin-gateway.env',original=readFileSync(envfile,'utf8');let browser;
const compose=async args=>{const r=await run('docker',['compose',...args],{timeout:120000});return r.stdout+r.stderr;};
async function create(title){const r=await request('/session',{method:'POST',cookie,body:{title}});assert.equal(r.status,200);return JSON.parse(r.body).id;}
async function idle(deadline=90000){const end=Date.now()+deadline;while(Date.now()<end){const r=await request('/session/status',{cookie});if(r.status===200&&Object.keys(JSON.parse(r.body)).length===0)return;await new Promise(r=>setTimeout(r,1000));}throw new Error('Native state did not become idle within fault deadline');}
async function ready(){for(let i=0;i<45;i++){try{const r=await request('/__platform/me',{cookie});if(r.status===200&&JSON.parse(r.body).ready)return;}catch{}await new Promise(r=>setTimeout(r,1000));}throw new Error('Native recovery not ready');}
const body=text=>({messageID:'msg_'+randomBytes(16).toString('hex'),model:{providerID:'approved',modelID:'gpt-5.6-luna'},parts:[{type:'text',text}]});
try{
 await idle();browser=await chromium.launch({headless:true,executablePath:'/snap/bin/chromium',args:['--no-sandbox']});const ctx=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000}});let page=await ctx.newPage();page.on('response',async r=>{if(r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/prompt_async')){const data=r.request().postDataJSON();writeFileSync('evidence/a08-ui-admission.json',JSON.stringify({status:r.status(),keys:Object.keys(data),messageID:data.messageID,messageId:data.messageId,detail:r.status()>=400?await r.text():''},null,2));}});await page.goto(cfg.origin+'/__platform/login');await page.locator('input[name=username]').fill('admin');await page.locator('input[name=password]').fill(cfg.users.admin.password);await page.locator('#login button').click();await page.waitForURL(cfg.origin+'/');
 const failing=await create('A08 actual approved model unavailable');writeFileSync(envfile,original.replace(/^MODEL_UPSTREAM=.*$/m,'MODEL_UPSTREAM=http://127.0.0.1:1'),{mode:0o600});writeFileSync('evidence/a08-model-fault-recreate.log',await compose(['up','-d','--no-build','--force-recreate','admin-model-gateway']));
 await page.goto(cfg.origin+'/server/'+Buffer.from(cfg.origin).toString('base64url')+'/session/'+failing);await page.getByRole('textbox',{name:'Prompt',exact:true}).waitFor();await page.getByRole('textbox',{name:'Prompt',exact:true}).fill('Report model connectivity; do not execute commands or write files.');const ack=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/prompt_async'));await page.getByRole('button',{name:'Send',exact:true}).click();assert.equal((await ack).status(),204);await new Promise(r=>setTimeout(r,1000));await idle();
 const fm=JSON.parse((await request('/session/'+failing+'/message',{cookie})).body);assert.equal(fm.filter(m=>m.info.role==='user').length,1);assert.ok(fm.some(m=>m.info.error));await page.screenshot({path:'evidence/a08-model-error.png',fullPage:true});writeFileSync('evidence/a08-model-error.json',JSON.stringify({session:failing,native:fm,visibleText:await page.locator('body').innerText()},null,2));assert.match(await page.locator('body').innerText(),/unavailable|error|API|502/i);pass('unavailable genuine model renders native error with one user message and no fallback');
 writeFileSync(envfile,original,{mode:0o600});await compose(['up','-d','--no-build','--force-recreate','admin-model-gateway']);await ready();
 writeFileSync('evidence/a08-environment-stop.log',await compose(['stop','admin-native-guard','admin-native']));const unready=await request('/__platform/me',{cookie});assert.equal(unready.status,503);await page.reload();await page.waitForLoadState('domcontentloaded');assert.match(await page.locator('body').innerText(),/unavailable|outcome/i);await page.screenshot({path:'evidence/a08-environment-unready.png',fullPage:true});pass('not-ready environment returns explicit 503 to browser');
 await compose(['up','-d','--no-build','--force-recreate','admin-native','admin-native-firewall','admin-native-guard']);await ready();
 const interrupted=await create('A08 discarded receipt and interrupted harmless Bash');const task=body('Run exactly sleep 120 using Bash. Do not write or read any files. This tests process interruption, not a successful result.');
 // Drop the real socket at response headers and intentionally discard the acknowledgement.
 await new Promise((resolve,reject)=>{const r=https.request(cfg.origin+'/session/'+interrupted+'/prompt_async',{method:'POST',rejectUnauthorized:false,headers:{Cookie:cookie,Origin:cfg.origin,'Content-Type':'application/json'}},res=>{res.destroy();r.destroy();resolve();});r.on('error',e=>e.code==='ECONNRESET'?resolve():reject(e));r.end(JSON.stringify(task));});
 const accepted=await request('/session/'+interrupted+'/message/'+task.messageID,{cookie});assert.equal(accepted.status,200);assert.equal((await request('/session/'+interrupted+'/prompt_async',{method:'POST',cookie,body:task})).status,409);pass('discarded real receipt checked through native message ID; resubmission rejected');
 let running=false;for(let i=0;i<90;i++){const m=JSON.parse((await request('/session/'+interrupted+'/message',{cookie})).body);running=m.some(x=>x.parts?.some(p=>p.type==='tool'&&p.tool==='bash'&&p.state.status==='running'&&p.state.input.command.includes('sleep 120')));if(running)break;await new Promise(r=>setTimeout(r,1000));}assert.ok(running,'Harmless real Bash must be executing');
 const url=cfg.origin+'/server/'+Buffer.from(cfg.origin).toString('base64url')+'/session/'+interrupted;await page.goto(url);await page.getByRole('textbox',{name:'Prompt',exact:true}).waitFor();await page.close();page=await ctx.newPage();await page.goto(url);await page.getByRole('textbox',{name:'Prompt',exact:true}).waitFor();assert.ok(Object.keys(JSON.parse((await request('/session/status',{cookie})).body)).includes(interrupted));pass('active browser close and reenter queries same native busy session without resend');
 writeFileSync('evidence/a08-process-kill.log',await compose(['kill','-s','SIGKILL','admin-native']));await compose(['up','-d','--no-build','--force-recreate','admin-native','admin-native-firewall','admin-native-guard']);await ready();await page.reload();await page.getByRole('textbox',{name:'Prompt',exact:true}).waitFor();
 const after=JSON.parse((await request('/session/'+interrupted+'/message',{cookie})).body);assert.equal(after.filter(m=>m.info.role==='user').length,1);const tools=after.flatMap(m=>m.parts||[]).filter(p=>p.type==='tool'&&p.tool==='bash');assert.ok(tools.length===1);assert.ok(tools[0].state.status!=='completed','Interrupted command must not be successful');writeFileSync('evidence/a08-interrupted-native.json',JSON.stringify({session:interrupted,messageID:task.messageID,messages:after,status:JSON.parse((await request('/session/status',{cookie})).body),visibleText:await page.locator('body').innerText()},null,2));await page.screenshot({path:'evidence/a08-interrupted.png',fullPage:true});pass('hard process interruption preserves one native task and does not mark command successful or replay it');
 result.status='PASS';
}catch(e){result.status='FAIL';result.error=e.message;throw e;}finally{writeFileSync(envfile,original,{mode:0o600});writeFileSync('evidence/a08-faults-result.json',JSON.stringify(result,null,2));await compose(['up','-d','--no-build','--force-recreate','admin-model-gateway','admin-native','admin-native-firewall','admin-native-guard']);if(browser)await browser.close();}
