import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {cfg} from './live-client.mjs';
import {chromium} from '/home/vmware/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const sid=JSON.parse(readFileSync('evidence/browser-flow-result.json')).session;
const browser=await chromium.launch({headless:true,executablePath:'/snap/bin/chromium',args:['--no-sandbox']});
const result={status:'IN_PROGRESS',session:sid};
try{const ctx=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000}});const page=await ctx.newPage();const network=[];page.on('response',r=>network.push({method:r.request().method(),path:new URL(r.url()).pathname,status:r.status()}));await page.goto(cfg.origin+'/__platform/login');await page.locator('input[name=username]').fill('admin');await page.locator('input[name=password]').fill(cfg.users.admin.password);await page.locator('#login button').click();await page.waitForURL(cfg.origin+'/');await page.goto(cfg.origin+'/server/'+Buffer.from(cfg.origin).toString('base64url')+'/session/'+sid);await page.getByRole('textbox',{name:'Prompt',exact:true}).waitFor();
 const before=await (await ctx.request.get(cfg.origin+'/session/'+sid+'/message')).json();
 const task='Verify this persistent authorized project after normal restart: run node --experimental-strip-types --test opencode-cloud/test/patch-export.test.mjs without modifying any files. Report actual test results.';writeFileSync('evidence/final-ui-task.txt',task+'\n');await page.getByRole('textbox',{name:'Prompt',exact:true}).fill(task);const ack=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/prompt_async'));await page.getByRole('button',{name:'Send',exact:true}).click();assert.equal((await ack).status(),204);
 let messages;const deadline=Date.now()+300000;while(Date.now()<deadline){await new Promise(r=>setTimeout(r,1500));const st=await ctx.request.get(cfg.origin+'/session/status');if(st.ok()&&Object.keys(await st.json()).length===0){const m=await (await ctx.request.get(cfg.origin+'/session/'+sid+'/message')).json();if(m.slice(before.length).some(x=>x.parts?.some(p=>p.type==='tool'&&p.tool==='bash'&&p.state.status==='completed'&&p.state.output.includes('# pass 3')&&p.state.output.includes('# fail 0')))){messages=m;break;}}}assert.ok(messages);await page.screenshot({path:'evidence/final-user-workbench.png',fullPage:true});writeFileSync('evidence/final-ui-native-messages.json',JSON.stringify(messages,null,2));result.status='PASS';result.network=network;result.newUserMessages=messages.slice(before.length).filter(m=>m.info.role==='user').length;assert.equal(result.newUserMessages,1);console.log('PASS final real browser submission, native Bash 3 tests, persistent session; one user message');
}catch(e){result.status='FAIL';result.error=e.message;throw e;}finally{writeFileSync('evidence/final-ui-result.json',JSON.stringify(result,null,2));await browser.close();}
