import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {cfg} from './live-client.mjs';
import {chromium} from '/home/vmware/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const result={status:'IN_PROGRESS'};const browser=await chromium.launch({headless:true,executablePath:'/snap/bin/chromium',args:['--no-sandbox']});let ctx,pty;
try{ctx=await browser.newContext({ignoreHTTPSErrors:true});const page=await ctx.newPage();await page.goto(cfg.origin+'/__platform/login');await page.locator('input[name=username]').fill('admin');await page.locator('input[name=password]').fill(cfg.users.admin.password);await page.locator('#login button').click();await page.waitForURL(cfg.origin+'/');const r=await ctx.request.post(cfg.origin+'/pty',{headers:{Origin:cfg.origin},data:{command:'bash',cwd:'/workspace/project',title:'controlled native terminal verification'}});assert.equal(r.status(),200);pty=(await r.json()).id;result.pty=pty;
 const tr=await ctx.request.post(cfg.origin+'/pty/'+pty+'/connect-token',{headers:{Origin:cfg.origin,'x-opencode-ticket':'1'}});assert.equal(tr.status(),200);const ticket=(await tr.json()).ticket;assert.ok(ticket);
 const out=await page.evaluate(async ({id,ticket})=>new Promise((resolve,reject)=>{const ws=new WebSocket(location.origin.replace('https:','wss:')+'/pty/'+id+'/connect?cursor=0&ticket='+encodeURIComponent(ticket));window.nativeTerminalSocket=ws;let output='';const timer=setTimeout(()=>{ws.close();reject(Error('Native terminal output deadline'));},15000);ws.binaryType='arraybuffer';ws.onopen=()=>ws.send("printf 'A03_NATIVE_PTY_OK\\n'\n");ws.onmessage=e=>{output+=typeof e.data==='string'?e.data:new TextDecoder().decode(e.data);if(output.includes('A03_NATIVE_PTY_OK\r\n')){clearTimeout(timer);resolve(output)}};ws.onerror=()=>{clearTimeout(timer);reject(Error('Native WebSocket failed'));};}),{id:pty,ticket});assert.match(out,/A03_NATIVE_PTY_OK/);const off=await ctx.request.post(cfg.origin+'/api/auth/logout',{headers:{Origin:cfg.origin}});assert.equal(off.status(),204);await page.waitForFunction(()=>window.nativeTerminalSocket?.readyState===WebSocket.CLOSED,{timeout:5000});result.logoutClosesNativeWebSocket=true;result.status='PASS';result.output=out;console.log('PASS real browser WebSocket to native Bash PTY');
}catch(e){result.status='FAIL';result.error=e.message;throw e;}finally{if(pty&&ctx){await ctx.request.post(cfg.origin+'/api/auth/login',{headers:{Origin:cfg.origin},data:{username:'admin',password:cfg.users.admin.password}});await ctx.request.delete(cfg.origin+'/pty/'+pty,{headers:{Origin:cfg.origin}});}writeFileSync('evidence/a03-terminal-result.json',JSON.stringify(result,null,2));await browser.close();}
