import {createSignal,For,onMount,Show} from 'solid-js'
export function Deliverables(props:{session?:string;close:()=>void}) {
 const [status,setStatus]=createSignal<any>();const [busy,setBusy]=createSignal(false);const [error,setError]=createSignal('');const [log,setLog]=createSignal('');const [records,setRecords]=createSignal<any>();const [link,setLink]=createSignal('')
 async function api(action:string,method='GET'){const r=await fetch('/__platform/preview/'+action,{method});const b=await r.json();if(!r.ok)throw Error(b.detail||'环境操作失败');return b}
 async function run(fn:()=>Promise<void>){if(busy())return;setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const refresh=()=>run(async()=>{setStatus(await api('status'));setLog((await api('log')).output);if(props.session)setRecords(await api('verification?session='+encodeURIComponent(props.session)))})
 onMount(refresh)
 async function openPreview(){const popup=window.open('about:blank','_blank');if(popup)popup.opener=null;await run(async()=>{try{const b=await api('ticket','POST');setLink(b.url);if(popup)popup.location.href=b.url}catch(e){popup?.close();throw e}})}
 async function download(path:string,name:string){await run(async()=>{const r=await fetch(path);if(!r.ok){const b=await r.json();throw Error(b.detail||'下载失败')}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)})}
 return <section class="wb-dialog wb-deliverables" role="dialog" aria-modal="true" aria-label="项目成果"><header><h2>项目成果</h2><button class="wb-icon" aria-label="关闭成果" onClick={props.close}>×</button></header>
 <p class="wb-muted">网页目录 web · 本人独立预览 · 源码与会话持续保存</p><Show when={error()}><p class="wb-error" role="alert">{error()}</p></Show>
 <div class="wb-result-actions"><button class="wb-outline" disabled={busy()} onClick={()=>run(async()=>{setStatus(await api('start','POST'));setLog((await api('log')).output)})}>启动预览</button><button class="wb-outline" disabled={busy()||!status()?.running} onClick={openPreview}>打开预览 ↗</button><button class="wb-outline" disabled={busy()} onClick={()=>run(async()=>{setStatus(await api('stop','POST'));setLog((await api('log')).output)})}>停止预览</button><button class="wb-outline" disabled={busy()} onClick={refresh}>刷新状态</button></div>
 <p class="wb-muted" aria-live="polite">{busy()?'正在操作…':status()?.running?'预览运行中（原生 PTY）':status()?.pty?'进程存在，等待就绪；请检查日志':'预览未启动'} · {status()?.pty||'无预览进程'}</p><Show when={link()}><a href={link()} target="_blank" rel="noopener">进入预览（一次性入口，30秒有效） ↗</a></Show>
 <details open><summary>运行日志</summary><pre class="wb-result-output">{log()||'暂无运行日志。首次启动需要 web/index.html。'}</pre></details>
 <div class="wb-result-actions"><button class="wb-primary" disabled={busy()} onClick={()=>download('/__platform/source.zip','WorkBench-source.zip')}>下载源码 ZIP ↓</button><button class="wb-outline" disabled={busy()} onClick={()=>download('/__platform/download','workbench-opencode.patch')}>下载补丁 ↓</button></div><p class="wb-muted">ZIP 包含当前完整源码和运行说明；依赖、密钥、缓存与浏览器制品不导出。任务运行时请先停止或等待完成。</p>
 <h3>当前会话验证结果</h3><Show when={props.session} fallback={<p class="wb-muted">请进入一个原生会话查看命令和截图。</p>}><p class="wb-muted">{props.session} · 原生工具命令、退出码和输出。退出 0 不等同于网页断言通过，缺少可信退出码显示“未确认”。</p><For each={records()?.screenshots}>{name=><a class="wb-screenshot" href={'/__platform/preview/screenshot?session='+encodeURIComponent(props.session!)+'&name='+encodeURIComponent(name)} target="_blank" rel="noopener"><img alt={'原生浏览器截图 '+name} src={'/__platform/preview/screenshot?session='+encodeURIComponent(props.session!)+'&name='+encodeURIComponent(name)}/><span>{name} ↗</span></a>}</For><For each={records()?.commands}>{c=><details><summary>{c.result} · {c.command.slice(0,110)}</summary><pre class="wb-result-output">{c.command+'\n\n退出码：'+(c.exit===null?'未确认':c.exit)+'\n'+c.output}</pre></details>}</For><Show when={!records()?.commands?.length}><p class="wb-muted">当前会话尚无原生 Bash 验证记录。</p></Show></Show>
 </section>
}
