import {createEffect,createSignal,onCleanup,onMount,Show,type Accessor} from 'solid-js'
import {PreviewTrigger} from './preview-policy'
type Options={session:Accessor<string|undefined>;nativeStatus:Accessor<Record<string,{type:string}|undefined>>}
export function createPreview(options:Options){
 const [status,setStatus]=createSignal<any>();const [open,setOpen]=createSignal(false);const [url,setUrl]=createSignal('');const [busy,setBusy]=createSignal(false);const [error,setError]=createSignal('');const [log,setLog]=createSignal('');const [mobile,setMobile]=createSignal(false);const [tab,setTab]=createSignal<'session'|'preview'|'changes'>('session');const [width,setWidth]=createSignal(50);
 const trigger=new PreviewTrigger();const preference='workbench-preview-closed';let expiryTimer:ReturnType<typeof setTimeout>|undefined,stopped=false,finishing=false;
 const [embedded,setEmbedded]=createSignal(false);const originReady=fetch('/__platform/me').then(r=>{if(!r.ok)throw Error('无法取得本人预览来源');return r.json()}).then(me=>{setEmbedded(me.embedded_preview===true&&me.workbench_origin===location.origin);return true}).catch(e=>{setError(String(e));return false});const suppressed=()=>document.cookie.split('; ').includes(preference+'=true')||localStorage.getItem(preference)==='true';const saveClosed=(closed:boolean)=>{document.cookie=preference+'='+(closed?'true':'')+'; Path=/; SameSite=Lax; Max-Age='+(closed?31536000:0)+(location.protocol==='https:'?'; Secure':'');if(closed)localStorage.setItem(preference,'true');else localStorage.removeItem(preference)};const environmentBusy=()=>Object.values(options.nativeStatus()).some(s=>s&&s.type!=='idle');
 async function api(action:string,method='GET'){const r=await fetch('/__platform/preview/'+action,{method});const b=await r.json();if(!r.ok)throw Error(b.detail||'预览操作失败');return b}
 async function refresh(){const b=await api('status');setStatus(b);return b}
 async function authorize(){const t=await api('ticket','POST');setUrl(t.url);clearTimeout(expiryTimer);expiryTimer=setTimeout(()=>{setUrl('');setError('预览授权已到期，点击刷新重新授权。')},1800000)}
 async function show(automatic=false){if(busy()||stopped)return;if(!await originReady)return;if(automatic&&(!embedded()||suppressed()))return;if(!automatic)saveClosed(false);const popup=!embedded()?window.open('about:blank','_blank'):null;if(popup)popup.opener=null;setBusy(true);setError('');setLog('');if(!automatic&&embedded()){setOpen(true);setTab('preview')}try{const s=await api('start','POST');if(!s.running)throw Error('网页服务尚未就绪');setStatus(s);if(!embedded()){const t=await api('ticket','POST');if(popup)popup.location.href=t.url;else throw Error('请允许打开本人预览标签页');return;}if(!url())await authorize();if(automatic){setOpen(true);setTab('preview')}}catch(e){popup?.close();setUrl('');setError(e instanceof Error?e.message:String(e));try{setLog((await api('log')).output)}catch{}}finally{setBusy(false)}}
 async function reload(){if(busy())return;setBusy(true);setError('');try{const s=await refresh();if(!s.running){setError('预览未运行，点击启动预览。');setUrl('');return;}setUrl('');await authorize()}catch(e){setError(String(e));setUrl('')}finally{setBusy(false)}}
 function close(){saveClosed(true);setOpen(false);setTab('session');setUrl('');clearTimeout(expiryTimer)}
 async function stop(){try{setStatus(await api('stop','POST'));setUrl('');clearTimeout(expiryTimer);setError('预览已停止，点击启动预览恢复。')}catch(e){setError(String(e))}}
 createEffect(()=>{const sid=options.session();const generation=trigger.enter(sid);if(!sid)return;void refresh().then(s=>trigger.seed(generation,s.web?.available?s.web.fingerprint:null)).catch(()=>{})});
 createEffect(()=>{const sid=options.session();const running=!!sid&&options.nativeStatus()[sid]?.type!=='idle'&&!!options.nativeStatus()[sid];if(!trigger.state(running))return;const generation=trigger.generation;finishing=true;void refresh().then(s=>{if(generation!==trigger.generation)return;if(s.web?.present&&!s.web?.available&&!suppressed()){setError('网页暂不能预览：'+s.web.reason);return;}if(trigger.changed(generation,!!s.web?.available,s.web?.fingerprint||null,environmentBusy()||s.nativeBusy))return show(true)}).catch(()=>{}).finally(()=>{finishing=false})});
 onMount(()=>{const saved=Number(localStorage.getItem('workbench-preview-width'));if(saved>=25&&saved<=75)setWidth(saved);const mq=matchMedia('(max-width:900px)');const resize=()=>setMobile(mq.matches);resize();mq.addEventListener('change',resize);void refresh().catch(()=>{});const interval=setInterval(()=>{if(document.visibilityState==='visible'){const generation=trigger.generation;void refresh().then(s=>{if(generation===trigger.generation&&!trigger.running&&!trigger.armed&&!finishing)trigger.baseline=s.web?.available?s.web.fingerprint:null}).catch(()=>{})}},5000);onCleanup(()=>{stopped=true;clearInterval(interval);clearTimeout(expiryTimer);mq.removeEventListener('change',resize)})});
 function resize(percent:number){const value=Math.min(75,Math.max(25,percent));setWidth(value);localStorage.setItem('workbench-preview-width',String(value))}
 return {status,open,url,busy,error,log,show,close,stop,reload,refresh,api,mobile,tab,setTab,width,resize}
}
export function PreviewPanel(props:{preview:ReturnType<typeof createPreview>}){const p=props.preview;const [copyFeedback,setCopyFeedback]=createSignal('');const publicAddress=()=>p.url()?new URL(p.url()).origin+'/':'';
 async function copyAddress(){try{await navigator.clipboard.writeText(publicAddress());setCopyFeedback('已复制：请在当前浏览器打开。')}catch{setCopyFeedback('无法自动复制，请选中上方地址手动复制。')}}
 async function external(){const popup=window.open('about:blank','_blank');if(popup)popup.opener=null;try{const t=await p.api('ticket','POST');if(popup)popup.location.href=t.url}catch{popup?.close()}}
 return <aside class="wb-preview" aria-label="网页预览" style={{width:p.mobile()?'100%':p.width()+'%'}}><header><strong>网页预览</strong><div><button disabled={p.busy()} onClick={p.reload}>刷新</button><button onClick={external} disabled={!p.status()?.running}>新标签 ↗</button><button onClick={p.stop} disabled={!p.status()?.pty||p.busy()}>停止</button><button aria-label="关闭预览" onClick={p.close}>×</button></div></header><Show when={p.error()}><div class="wb-error" role="alert">{p.error()}<button disabled={p.busy()} onClick={()=>p.show()}>启动预览</button></div><pre class="wb-result-output">{p.log()}</pre></Show><Show when={p.busy()}><p class="wb-muted">正在启动并授权本人网页…</p></Show><Show when={p.url()}><iframe title="本人网页预览" src={p.url()} sandbox="allow-scripts allow-forms allow-same-origin" referrerpolicy="no-referrer" /></Show><footer><p>5173 是容器内部地址，请使用这里的预览入口。</p><details><summary>预览地址与访问说明</summary><Show when={publicAddress()}><label>用户预览地址<input aria-label="用户预览地址" readonly value={publicAddress()} onFocus={e=>e.currentTarget.select()}/></label><button onClick={copyAddress}>复制预览地址</button><p role="status">{copyFeedback()}</p></Show><p>当前浏览器授权后可访问。内网部署需连接企业网络；本机 localhost 地址仅在这台电脑使用。另一浏览器需先登录工作台并点击“预览”。不要复制一次性授权链接。</p></details></footer></aside>
}
export function PreviewResize(props:{preview:ReturnType<typeof createPreview>}){const p=props.preview;let cleanup=()=>{};onCleanup(()=>cleanup());function start(e:PointerEvent){e.preventDefault();const box=(e.currentTarget as HTMLElement).parentElement!.getBoundingClientRect();const move=(event:PointerEvent)=>p.resize(100*(box.right-event.clientX)/box.width);const done=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',done);document.body.classList.remove('wb-resizing')};cleanup();cleanup=done;document.body.classList.add('wb-resizing');document.addEventListener('pointermove',move);document.addEventListener('pointerup',done,{once:true})}
 return <div class="wb-preview-resize" role="separator" aria-label="调整预览宽度" aria-orientation="vertical" aria-valuemin={25} aria-valuemax={75} aria-valuenow={p.width()} tabindex="0" onPointerDown={start} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();p.resize(p.width()+(e.key==='ArrowLeft'?5:-5))}}}/>
}
