import {readFile,realpath,readdir,lstat,open} from 'node:fs/promises';
import path from 'node:path';
import {webProject} from './web-project.mjs';
const root='/workspace/project';const title='WorkBench preview :5173';
export function previewRuntime(authorization:string){
 const request=async(route:string,method='GET',body?:any)=>{const r=await fetch('http://127.0.0.1:4030'+route+(route.includes('?')?'&':'?')+'directory='+encodeURIComponent(root),{method,headers:{Authorization:authorization,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Native request failed: '+r.status);return r.status===204?undefined:await r.json() as any;};
 let changing=false;
 async function healthy(){try{const r=await fetch('http://127.0.0.1:5173/',{signal:AbortSignal.timeout(1500)});return r.ok;}catch{return false;}}
 async function status(){const web=await webProject();const nativeBusy=Object.values(await request('/session/status')).some((s:any)=>s.type!=='idle');const ptys=await request('/pty');const pty=ptys.find((p:any)=>p.title===title&&p.status==='running');return {web,nativeBusy,running:!!pty&&await healthy(),pty:pty?.id,port:5173,directory:root+'/web',processState:pty?.status||'stopped'};}
 async function start(){if(changing)throw Error('Preview transition in progress');changing=true;try{const s=await status();if(s.running)return s;if(!s.web.available)throw Error(s.web.reason);if(s.pty)throw Error('Preview process exists but is not ready; inspect logs and stop before restarting');if(Object.values(await request('/session/status')).some((s:any)=>s.type!=='idle'))throw Error('原生任务仍在运行；预览未启动');if(await healthy())throw Error('Port 5173 is occupied by another process; nothing was replaced');const web=await realpath(root+'/web');if(web!==root+'/web')throw Error('Preview root must be a real web directory');await lstat(web+'/index.html');const pty=await request('/pty','POST',{command:'/bin/bash',args:['/trusted/start-preview.sh'],cwd:root,title});for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,250));if(await healthy())return {...await status(),pty:pty.id};}try{await request('/pty/'+pty.id,'DELETE')}catch{}throw Error('Preview failed to start; inspect the native runtime log');}finally{changing=false;}}
 async function stop(){if(changing)throw Error('Preview transition in progress');changing=true;try{for(const p of await request('/pty'))if(p.title===title)await request('/pty/'+p.id,'DELETE');for(let i=0;i<20&&await healthy();i++)await new Promise(r=>setTimeout(r,100));if(await healthy())throw Error('Port remains occupied; maintainer investigation required');return await status();}finally{changing=false;}}
 async function log(){const file=root+'/.workbench-artifacts/preview.log';try{if(await realpath(file)!==file)throw Error('Unsafe preview log');const f=await open(file,'r');try{const size=(await f.stat()).size;const b=Buffer.alloc(Math.min(size,128*1024));await f.read(b,0,b.length,Math.max(0,size-b.length));return b.toString();}finally{await f.close();}}catch(e:any){if(e.code==='ENOENT')return '';throw e;}}
 async function verification(sid:string){if(!/^ses_[\w-]+$/.test(sid))throw Error('Invalid native session');const session=await request('/session/'+sid);if(session.directory!==root)throw Error('Session outside the authorized project');const messages=await request('/session/'+sid+'/message');const commands=messages.flatMap((m:any)=>(m.parts||[]).filter((p:any)=>p.type==='tool'&&p.tool==='bash').map((p:any)=>({message:m.info.id,part:p.id,command:p.state.input?.command||'',toolState:p.state.status,exit:Number.isInteger(p.state.metadata?.exit)?p.state.metadata.exit:null,result:Number.isInteger(p.state.metadata?.exit)&&p.state.status==='completed'?(p.state.metadata.exit===0?'命令退出 0':'命令失败'):'未确认',output:p.state.output||p.state.error||'',time:p.state.time})));
 for(const c of commands)if(c.command.includes('playwright-cli')&&c.output.includes('### Error'))c.result='CLI 返回错误（见原始输出）';
 const directory=root+'/.workbench-artifacts/'+sid;let screenshots:string[]=[];try{if(await realpath(directory)!==directory)throw Error('Unsafe artifact directory');screenshots=(await readdir(directory)).filter(n=>/^[\w.-]+\.png$/.test(n)).slice(0,32);}catch(e:any){if(e.code!=='ENOENT')throw e;}return {session:sid,title:session.title,commands,screenshots,note:'原生 Bash 退出状态，不以模型总结判定通过；Playwright 的 ### Error 即使退出 0 也须检查。'};
 }
 async function screenshot(sid:string,name:string){const v=await verification(sid);if(!v.screenshots.includes(name))throw Error('Screenshot not in this native session');const file=root+'/.workbench-artifacts/'+sid+'/'+name;if(await realpath(file)!==file)throw Error('Unsafe screenshot link');const stat=await lstat(file);if(!stat.isFile()||stat.size>8*1024*1024)throw Error('Invalid screenshot size');const b=await readFile(file);if(b.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('Invalid PNG');return b;}
 return {status,start,stop,log,verification,screenshot};
}
