import http from 'node:http';
import {isCredentialCookie} from './preview-origin.mjs';
const hop=new Set(['connection','keep-alive','proxy-authenticate','proxy-authorization','te','trailer','transfer-encoding','upgrade']);
function headers(input){const blocked=new Set([...hop,...String(input.connection||'').toLowerCase().split(',').map(s=>s.trim())]);return Object.fromEntries(Object.entries(input).filter(([k])=>!blocked.has(k)&&!['authorization','host','forwarded'].includes(k)&&!k.startsWith('x-')));}
export function appCookie(value){return String(value||'').split(';').filter(s=>!isCredentialCookie(s)).join(';');}
export function previewProxy(req,res,{target,pathname,password,register,frameAncestor}){
 const url=new URL(pathname,target),h=headers(req.headers);h.host=url.host;h.cookie=appCookie(h.cookie);if(password)h.authorization='Basic '+Buffer.from('opencode:'+password).toString('base64');
 const upstream=http.request(url,{method:req.method,headers:h},reply=>{const out=headers(reply.headers);if(frameAncestor){delete out['x-frame-options'];const csp=String(out['content-security-policy']||'').split(';').filter(d=>!/^\s*frame-ancestors\b/i.test(d)).filter(Boolean);out['content-security-policy']=[...csp,'frame-ancestors '+frameAncestor].join('; ');} out['cache-control']='no-store';out['x-content-type-options']='nosniff';out['referrer-policy']='no-referrer';if(out['set-cookie'])out['set-cookie']=out['set-cookie'].filter(s=>!isCredentialCookie(s));if(reply.headers.location){const redirect=new URL(reply.headers.location,url);if(redirect.origin!==url.origin){reply.destroy();res.writeHead(502);res.end('External preview redirect refused');return;}out.location=redirect.pathname+redirect.search;}res.writeHead(reply.statusCode||502,out);reply.on('error',()=>res.destroy());reply.pipe(res);});
 const off=register?.(()=>{upstream.destroy();res.destroy();});res.once('close',()=>{off?.();upstream.destroy();});req.once('aborted',()=>upstream.destroy());upstream.setTimeout(120000,()=>upstream.destroy());upstream.on('error',()=>{if(res.headersSent)res.destroy();else{res.writeHead(503,{'Content-Type':'text/plain','Cache-Control':'no-store'});res.end('Preview is not running; start it from WorkBench.');}});req.pipe(upstream);
}
export function previewUpgrade(req,socket,head,{target,pathname,password,register}){
 const url=new URL(pathname,target),h=headers(req.headers);h.host=url.host;h.cookie=appCookie(h.cookie);h.connection='Upgrade';h.upgrade='websocket';if(password)h.authorization='Basic '+Buffer.from('opencode:'+password).toString('base64');h.origin='http://127.0.0.1:5173';
 const request=http.request(url,{headers:h});socket.on('error',()=>{request.destroy();socket.destroy();});request.on('upgrade',(reply,remote,remoteHead)=>{socket.write('HTTP/1.1 101 Switching Protocols\r\n'+Object.entries(reply.headers).filter(([k])=>!['set-cookie'].includes(k)).map(([k,v])=>`${k}: ${v}`).join('\r\n')+'\r\n\r\n');if(head.length)remote.write(head);if(remoteHead.length)socket.write(remoteHead);socket.pipe(remote);remote.pipe(socket);const off=register?.(()=>{remote.destroy();socket.destroy();});socket.on('close',()=>{off?.();remote.destroy();});socket.on('error',()=>remote.destroy());remote.on('close',()=>socket.destroy());remote.on('error',()=>socket.destroy());remote.setTimeout(120000,()=>remote.destroy());});request.on('response',r=>{r.resume();socket.end(`HTTP/1.1 ${r.statusCode} Rejected\r\nConnection: close\r\n\r\n`);});request.on('error',()=>socket.destroy());socket.on('close',()=>request.destroy());request.setTimeout(10000,()=>request.destroy());request.end();
}
